version: "latest"
services:
    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - ./app:/usr/src/app
        environment:
            - NODE_ENV=development
        working_dir: /usr/src/app
        command: npm run dev -- --host
