services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./app
          target: /usr/src/app
          ignore:
            - node_modules/
            - dist/

        - action: rebuild
          path: package.json
    networks:
      - public

  web:
    restart: always
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - public

networks:
  private:
    driver: bridge
  public:
    driver: bridge
