version: "3.9"
services:
    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        environment:
            - NODE_ENV=development
        develop:
            watch:
                - action: sync
                  path: ./app
                  target: /usr/src/app
                  ignore:
                      - node_modules/

                - action: rebuild
                  path: package.json
